-- ==========================================================
-- LAYER   : SILVER
-- OBJECT  : VIEW CUSTOMERS_CLEAN
-- ==========================================================

USE DATABASE RETAIL_ANALYTICS_QUANTIUM;

CREATE OR REPLACE VIEW SILVER.CUSTOMERS_CLEAN AS

SELECT 
    LYLTY_CARD_NBR AS CUSTOMER_ID,
    UPPER(TRIM(LIFESTAGE)) AS CUST_LIFESTAGE,
    UPPER(TRIM(PREMIUM_CUSTOMER)) AS CUST_SEGMENT_PREMIUM
FROM BRONZE.CUSTOMERS;
