-- ==========================================================
-- LAYER   : SILVER
-- OBJECT  : VIEW CUSTOMERS_ENRICHED
-- ==========================================================

USE DATABASE RETAIL_ANALYTICS_QUANTIUM;

CREATE OR REPLACE VIEW SILVER.CUSTOMERS_ENRICHED AS

SELECT 
    CUSTOMER_ID,
    CUST_SEGMENT_PREMIUM,

    -- Extraction de la maturité
    CASE 
        WHEN CUST_LIFESTAGE LIKE 'YOUNG%' THEN 'YOUNG'
        WHEN CUST_LIFESTAGE LIKE 'MIDAGE%' THEN 'MIDAGE'
        WHEN CUST_LIFESTAGE LIKE 'OLDER%' OR CUST_LIFESTAGE = 'RETIREES' THEN 'OLDER'
        ELSE 'MIDAGE'
    END AS CUST_AGE,

    -- Extraction de la structure du foyer
    CASE 
        WHEN CUST_LIFESTAGE LIKE '%FAMILIES' THEN 'FAMILIES'
        WHEN CUST_LIFESTAGE LIKE '%SINGLES/COUPLES' OR CUST_LIFESTAGE = 'RETIREES' THEN 'SINGLES/COUPLES'
        ELSE 'UNKNOWN'
    END AS CUST_FAMILY_TYPE
FROM SILVER.CUSTOMERS_CLEAN;
