-- ==========================================================
-- LAYER   : SILVER
-- OBJECT  : VIEW TRANSACTIONS_CLEAN
-- ==========================================================

USE DATABASE RETAIL_ANALYTICS_QUANTIUM;

CREATE OR REPLACE VIEW SILVER.TRANSACTIONS_CLEAN AS

SELECT DISTINCT
    TXN_ID,
    LYLTY_CARD_NBR AS CUSTOMER_ID,
    STORE_NBR AS STORE_ID,
    PROD_NBR AS PROD_ID,
    DATEADD(day, DATE, '1899-12-30')::DATE AS TXN_DATE,
    TOT_SALES AS SALES_AMNT,
    PROD_QTY AS SALES_QTY,
    UPPER(TRIM(REGEXP_REPLACE(PROD_NAME, ' {2,}', ' '))) AS PROD_NAME,
FROM BRONZE.TRANSACTIONS
WHERE 
    LYLTY_CARD_NBR <> 226000
    AND PROD_NAME NOT ILIKE '%SALSA%';
