-- ----------------------------------------------------------
-- 3. AUDIT QUALITÉ : TABLE TRANSACTIONS
-- ----------------------------------------------------------

USE DATABASE RETAIL_ANALYTICS_QUANTIUM;

-- TABLE TRANSACTIONS

-- A. Vérification des valeurs manquantes

SELECT 
    COUNT(*) - COUNT(DATE) AS MISSING_DATE,
    COUNT(*) - COUNT(STORE_NBR) AS MISSING_STORE_NBR,
    COUNT(*) - COUNT(LYLTY_CARD_NBR) AS MISSING_LYLTY_CARD_NBR,
    COUNT(*) - COUNT(TXN_ID) AS MISSING_TXN_ID,
    COUNT(*) - COUNT(PROD_NBR) AS MISSING_PROD_NBR,
    COUNT(*) - COUNT(PROD_NAME) AS MISSING_PROD_NAME,
    COUNT(*) - COUNT(PROD_QTY) AS MISSING_PROD_QTY,
    COUNT(*) - COUNT(TOT_SALES) AS MISSING_TOT_SALES
FROM BRONZE.TRANSACTIONS;

-- B. Détection des doublons

SELECT TXN_ID, PROD_NBR, COUNT(*)
FROM BRONZE.TRANSACTIONS
GROUP BY TXN_ID, PROD_NBR
HAVING COUNT(*) > 1;

SELECT *
FROM BRONZE.TRANSACTIONS
WHERE TXN_ID = 108462;

--- C. Detection des valeurs aberrantes

SELECT 
    MIN(TOT_SALES) AS min_sales,
    MAX(TOT_SALES) AS max_sales,
    MIN(PROD_QTY) AS min_qty,
    MAX(PROD_QTY) AS max_qty
FROM BRONZE.TRANSACTIONS;

SELECT *
FROM BRONZE.TRANSACTIONS
ORDER BY PROD_QTY DESC
LIMIT 10;

-- 4. ANALYSE DE LA FRÉQUENCE DES MOTS (PROD_NAME)

SELECT 
    UPPER(f.VALUE) AS clean_word, 
    COUNT(*)       AS frequency
FROM BRONZE.TRANSACTIONS,
LATERAL FLATTEN(INPUT => SPLIT(PROD_NAME, ' ')) f
WHERE clean_word NOT REGEXP '[0-9]+[gG]'  -- Ignore les poids (ex: 175g)
  AND clean_word NOT REGEXP '[&/\\-]'     -- Optionnel : ignore les caractères spéciaux
GROUP BY 1
ORDER BY 2 DESC;


-- TABLE TRANSACTIONS

-- A. Vérification des valeurs manquantes

SELECT 
    COUNT(*) - COUNT(LYLTY_CARD_NBR) AS MISSING_CARD_NBR,
    COUNT(*) - COUNT(LIFESTAGE) AS MISSING_LIFESTAGE,
    COUNT(*) - COUNT(PREMIUM_CUSTOMER) AS MISSING_PREMIUM
FROM BRONZE.CUSTOMERS;

-- B. Détection des doublons

SELECT LYLTY_CARD_NBR, COUNT(*)
FROM BRONZE.CUSTOMERS
GROUP BY LYLTY_CARD_NBR
HAVING COUNT(*) > 1;

-- B. Test d'uniformité

-- Valeurs uniques pour LIFESTAGE
SELECT DISTINCT LIFESTAGE 
FROM BRONZE.CUSTOMERS 
ORDER BY 1;

-- Valeurs uniques pour PREMIUM_CUSTOMER
SELECT DISTINCT PREMIUM_CUSTOMER 
FROM BRONZE.CUSTOMERS 
ORDER BY 1;